### ISSUE TITLE
"Required" error for username field on motosport.com

### ISSUE THREAD

**Issue by TheCodesterr** [LEDfan/keywi#101]
It will auto fill properly for my username and password for motosport.com, but when I click sign in it says my username is required. 

Disabled KeyWi, logged in manually and it worked fine.

**Comment by RobinJadoul** [comment]
The problem is most likely that the inputs don't see the changes (though we already try to force this).
Unfortunately, I can't reproduce right now because I cannot even connect to http://motosport.com (the connections times out)

You could try to do the keywi autofill, and then manually add and remove a character, e.g. type <kbd>space</kbd> <kbd>backspace</kbd>, for both username and password. That should hopefully work.

**Comment by TheCodesterr** [comment]
I tried that before this and it did not work. Thanks for the suggestion though. 

It is a secure website so the url is: https://www.motosport.com/

Hope this helps. Loving the add on by the way. Best one I've found.

**Comment by LEDfan** [comment]
Thanks for the kind works, this issue is fixed by #102. I'll release a new version.
