### ISSUE TITLE
Optional Remember Password to Unlock Secure Storage

### ISSUE THREAD

**Issue by Rictusempra** [LEDfan/keywi#106]
So that you don't have to enter password on every browser's start.

I don't find too much security issue as KeePassHTTP will always prompt the confirm dialog by default.

**Comment by RobinJadoul** [comment]
The entire Secure Storage is there because we want to avoid storing sensitive information related to the connection to KeepassHTTP where anyone can access it.
One option is to keep your password extremely simple (a single character works, an empty password not, it seems)
Alternatively, you can also try to use Keepass autotype to fill your Secure Storage password for you (I do it that way, keywi provides better integration in general browsing, but configuring a single key with autotype isn't too much work. Just change the autotype configuration for that entry to `{PASSWORD}{ENTER}`)

Finally, once it becomes available for webextensions, we hope to transition to using the Firefox password manager to store our connection information. This would allow for both a master password that is required to use keywi, or no password (in which case, of course, the connection information isn't securely stored at all), see #15

**Comment by LEDfan** [comment]
Just for reference to see that Firefox stores the information in clear text:
 1. go to `about:support`
 2. go to the path listed under `Application Basics` -> ` Profile Directory`
 3. navigate to `browser-extension-data/keywi-ff-add-on@ledfan.be` 
 4. data saved by Keywi is in the `storage.js` file, for example:

<details>

```

{
  "crypto_salt": "[114,55,90,165,88,121,219,228,0,50,198,108,172,21,168,139,1,194,94,217,123,210,160,59,152,121,170,58,126,65,223,54,126,239,44,144,197,138,110,111,164,255,182,10,77,119,6,255,188,248,189,188,24,188,233,168,197,130,139,109,165,152,146,128,203,146,98,149,254,143,153,65,166,108,150,105,212,35,229,135,204,163,232,175,39,162,29,151,189,184,178,207,248,85,228,169,120,67,93,215]",
  "local_secure_storage__encryption_key_test": {
    "nonce": "IA8EnfufLDhV5jUD913Y6w==",
    "verifier": "01EyMaOcFC+t1dVAtKNUF5r/X04INBFAvsYajDX0+8o="
  },
  "local_secure_storage__database.id": {
    "data": "0XIa91R+EV0Pjw8fFvMQ2A==",
    "nonce": "v0M5nLf722bfd0fzU7iukA==",
    "verifier": "S1sdy8iruPb0Ndz+Eh23MsU4v1kHuDGyBT2C592y2oQ="
  },
  "local_secure_storage__database.key": {
    "data": "bA+8pXOGVzM3pjdGYVZTo6uLhtYgUNEH6wDnc5fntvqN9oKLHa0JD7/kk/ylUz4G",
    "nonce": "HVk9dmKv+rZCAB41k0qzpQ==",
    "verifier": "j3BLaqKXdB3iuWJccAO5EXvtsU+GICoNpKtfz7uKroc="
  },
  "local_secure_storage__database.hash": {
    "data": "k9Uk+CseFP8AEGNAv97Yuif8ztaYUOg57aVLrzZjgpUpG1bmDDlYLkZMG3arrmoS",
    "nonce": "z5L3schtgLFtAU34d3dQ2w==",
    "verifier": "yzzdKv7FvFBJnR0c6hyYuLiCtAhKF2WkFyASxJMTyNE="
  }
}
```
</details>
