### ISSUE TITLE
Basic auth: when cancelling filling FF asks for credentials a second time

### ISSUE THREAD

**Issue by LEDfan** [LEDfan/keywi#112]
1. got to a basic auth website
 2. click cancel on Keywi baisc auth window
 3. click cancel on FF basic auth window -> FF opens 401 page
 4. keywi again opens the confirm dialog, if you now let it fill credentials nothing happens, because the page is already loaded. (a refresh however loads the page since FF caches the credentials)

The second time the credentials are asked is for the favicon (which FF automatically requests).

IMO as soon as the user has cancelled the confirmation window for one url and tab it shouldn't show up again.

I guess if we filter on the default favicon request this should already improve the UX a lot. The downside is that you can't use Keywi if you directly visit a url to a favicon, but IMO this isn't a problem.

@RobinJadoul what do you think?

**Comment by RobinJadoul** [comment]
> IMO as soon as the user has cancelled the confirmation window for one url and tab it shouldn't show up again.

We could keep a mapping from (tab, host) that lists combinations where we don't want to ask. The problem I see here is that one the one hand, a user might want to ignore for all pages on a certain host irrespective of tab, and on the other hand they may want to get the option to use keywi again after cancelling one time (perhaps because they wanted to do something else first and needed to dismiss the dialog) on the same tab, without the need to open it up in a new tab.

From a UX perspective, it's perhaps nice to have a possibility to have keywi basic auth ignore certain hosts or pages.

> I guess if we filter on the default favicon request this should already improve the UX a lot. The downside is that you can't use Keywi if you directly visit a url to a favicon, but IMO this isn't a problem.

I agree that this is a non-issue, if we go for that solution.

My proposed approach is:
1. Ignore the favicon for now (maybe we can even figure out a way to discover if the favicon isn't by chance the page being visited)
2. Add an extra configuration option where the user can choose a set of hosts/pages to ignore for basic auth (backlog)

**Comment by LEDfan** [comment]
> >  IMO as soon as the user has cancelled the confirmation window for one url and tab it shouldn't show up again.
> We could keep a mapping from (tab, host) that lists combinations where we don't want to ask....

I forgot to say it shouldn't show up during one page load. As soon as the user refreshes the page, the popup should show again.

> My proposed approach is:

Agree :+1:
