### ISSUE TITLE
Toolbar button

### ISSUE THREAD

**Issue by EMLVIRUS** [LEDfan/keywi#63]
like PassIFox, use a toolbar button to indicate status or some actions intead of those in about:addons where is too troublematic to visit.

**Comment by RobinJadoul** [comment]
For now, it seems there's no real advantage for adding a toolbar button, since everything that can only be done through the settings should not happen often (resetting settings, changing security settings for the secure storage, initial addon setup).
And, as stated in the description, we intend to keep this as nonintrusive as possible, which wouldn't justify a toolbar button with the current featureset just yet.

This can be reconsidered if we ever implement more advanced features such as support for multiple databases of multiple database providers (such as [Pass](https://www.passwordstore.org/))

So closing this for now. (Thanks for the feedback anyway)
