### ISSUE TITLE
Missing context menu for dynamically generated input[type=email]

### ISSUE THREAD

**Issue by Rictusempra** [LEDfan/keywi#78]
I'm sorry that I can only find a Chinese example
https://acg12.com/204686/
![image](https://user-images.githubusercontent.com/16912240/30646434-93b3f50e-9e4b-11e7-876b-e57106a63a7c.png)

Anyway, I will try to find more examples.

**Comment by LEDfan** [comment]
I have just tried to fill in credentials (which don't exist) and it seems to work fine.

I tried to create a test account, but it says something that the server is too busy.

What exactly doesn't work? Does the site say you didn't full in anything, or that the credentials are wrong although they are correct, or ...?

**Comment by RobinJadoul** [comment]
Hotkey filling works for me (dummy information), and I get a message that username and password don't match (thanks google translate :wink:). However, the context menu doesn't seem to work on the username field, which is an `input` element of type `email`.
I suspect some kind of problem with https://github.com/LEDfan/keywi/blob/master/content_scripts/fix-contentEditable.js because running the same code manually in the console makes the keywi entry appear in the context menu

**Comment by RobinJadoul** [comment]
I suspect this would be due to the actual input element being created at runtime instead of being inside the DOM from the start

**Comment by Rictusempra** [comment]
sorry for my mistakes, I thought it was blocked by JavaScript pop-ups

**Comment by RobinJadoul** [comment]
@Rictusempra Don't worry, analysing the problem is our task :slightly_smiling_face: Situations where the plugin doesn't work are issues anyway

**Comment by Rictusempra** [comment]
@LEDfan @RobinJadoul 
Hey, this bug seems also happening in [Outlook login page](https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1506497597&rver=6.7.6640.0&wp=MBI_SSL&wreply=https%3a%2f%2foutlook.live.com%2fmail%2f%3fauthRedirect%3dtrue%26nlp%3d1%26RpsCsrfState%3d746f8c7e-5869-2596-a918-82f6cafcc564&id=292841&CBCXT=out&fl=wld&cobrandid=90015#/inbox)
Could u give a try?

**Comment by RobinJadoul** [comment]
@Rictusempra This is an unrelated issue, being tracked in #80 right now, thanks for reporting
