### ISSUE TITLE
Abililty to remap autofill keyboard shortcut

### ISSUE THREAD

**Issue by TheCodesterr** [LEDfan/keywi#93]
My Mac uses the command key for control, so when I press command+shift+f, Firefox goes full screen. 

Alternatively, when I press control+shift+F, nothing happens.

**Comment by RobinJadoul** [comment]
It would indeed be <kbd>command</kbd>+<kbd>shift</kbd>+<kbd>f</kbd> for a mac, but it seems FF overrides this.

It seems firefox doesn't give an option to remap keys of itself, and adding this would require some reworking from us, so for now I'll transition to using <kbd>ctrl</kbd> everywhere, instead of using <kbd>command</kbd> on mac.

In the long run, we might want to invest some time in configurability of keyboard shortcuts, but I'm not sure if it'll be worth the effort.

**Comment by RobinJadoul** [comment]
I just noticed this is now a feature offered by firefox itself, so no burden on us to allow configuration here.
Our defaults still look sane to me, so I'm closing this.
